- name: Install Redis repo
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed

- name: Install a modularity appstream with defined stream
  ansible.builtin.dnf:
    name: "@redis:remi-6.2"
    state: installed

- name: Install Redis
  ansible.builtin.yum:
    name: redis
    state: installed

- name: Update Listener
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Enable and Start Mongodb
  ansible.builtin.systemd:
    state: restarted
    name: redis
    enabled: true







