#print_head "Enabling Nginx"
#systemctl enable nginx &>>${log_file}
#status_check $?
#print_head "Starting Nginx"
#systemctl restart nginx &>>${log_file}
#status_check $?

- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: remove old content/directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: Create a directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory

- name: Unarchive and downloaded Frontend
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copy file
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start and enable servier
  ansible.builtin.systemd:
    state: started
    name: nginx
    enabled: true


