#  schema_setup(){
#    if [ "${schema_type}" == "mongo" ]; then
#    print_head "Copy mongodb repo file"
#    cp ${code_dir}/configs/mongo.repo /etc/yum.repos.d/mongo.repo
#    status_check $?
#    print_head "Installing mongo client"
#    yum install mongodb-org-shell -y &>>"${log_file}"
#    status_check $?
#    print_head "Load Schema"
#    mongo --host mongodb-dev.shujadevops.online </app/schema/${component}.js &>>${log_file}
#    status_check $?
#    elif [ "${schema_type}" == "mysql" ]; then
#    print_head "Install mysql client"
#    yum install mysql -y &>>"${log_file}"
#    status_check $?
#    print_head "Load schema"
#    mysql -h mysql-dev.shujadevops.online -uroot -p${mysql_root_password} < /app/schema/shipping.sql &>>"${log_file}"
#    status_check $?
#    fi
#
#  }
- name: MongoDB Schema
  when: schema_type == "mongo"
  block:
    - name: Setup MongoDB repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install MongoDB Client
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed

    - name: Load Schema
      ansible.builtin.shell: mongo --host mongodb-dev.shujadevops.online </app/schema/{{component}}.js

- name: MySQL Schema
  when: schema_type == "mysql"
  block:
    - name: Install MySQL Client
      ansible.builtin.yum:
        name: mysql
        state: installed

    - name: Load Schema
      ansible.builtin.shell: mysql -h mysql-dev.shujadevops.online -uroot -pRoboShop@1 < /app/schema/{{ component }}.sql
